"""empty message

Revision ID: b3a60d8f67ce
Revises: 
Create Date: 2019-05-19 13:44:43.281565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a60d8f67ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('processed_text', sa.UnicodeText(), nullable=False),
    sa.Column('kad_case_num', sa.String(length=32), nullable=True),
    sa.Column('kad_case_id', sa.String(length=36), nullable=True),
    sa.Column('kad_doc_id', sa.String(length=36), nullable=True),
    sa.Column('kad_doc_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kad_case_id'),
    sa.UniqueConstraint('kad_case_num'),
    sa.UniqueConstraint('kad_doc_id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('document')
    # ### end Alembic commands ###
